import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Currency = 'Ar' | '€' | '$';
type Language = 'fr' | 'mg' | 'en';

interface SettingsContextType {
  currency: Currency;
  setCurrency: (c: Currency) => void;
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType>({
  currency: 'Ar',
  setCurrency: () => {},
  language: 'fr',
  setLanguage: () => {},
  t: (key) => key,
});

export const useSettings = () => useContext(SettingsContext);

const TRANSLATIONS = {
  fr: {
    'welcome': 'Bienvenue',
    'my_groceries': 'Mes Courses',
    'search': 'Rechercher...',
    'expenses': 'Dépenses',
    'articles': 'Articles',
    'recent_lists': 'Listes Récentes',
    'sort': 'Trier',
    'settings': 'Paramètres',
    'dark_mode': 'Mode Sombre',
    'language': 'Langue',
    'currency': 'Devise',
    'help': 'Aide & Astuces',
    'close': 'Fermer',
    'empty_list': 'Aucune liste trouvée',
    'new_list': 'Nouvelle Liste',
    'reports': 'Rapports',
    'choose_theme': 'Choisir un thème',
    'delete_list': 'Supprimer cette liste',
    'delete_list_confirm': 'Voulez-vous vraiment supprimer la liste',
    'delete': 'Supprimer',
    'cancel': 'Annuler',
    'tips_title': 'Astuces E-tsena',
    'tip_1': 'Utilisez le bouton + pour ajouter une liste.',
    'tip_2': 'Une liste vide ne sera pas enregistrée.',
    'tip_3': 'Appuyez sur ... pour les options (supprimer, rappel).',
    'tip_4': 'Consultez les rapports pour analyser vos dépenses.',
    'tip_5': 'Changez le thème et la langue dans les paramètres.',
    'understood': 'Compris',
    'sort_by': 'Trier par',
    'date': 'Date',
    'name': 'Nom',
    'amount': 'Montant',
    'reminder': 'Programmer un rappel (1h)',
    'reminder_set': 'Rappel programmé dans 1 heure.',
    'reminder_title': 'Rappel',
    'reminder_scheduled': 'Rappel programmé',
    'reminder_notif_text': 'Vous serez notifié le',
    'error': 'Erreur',
    'info': 'Info',
    'reminder_error': 'Impossible de programmer le rappel (date passée ?)',
    'total_spent': 'TOTAL DÉPENSÉ',
    'progress': 'Avancement',
    'to_buy': 'À ACHETER',
    'add_item_placeholder': 'Ajouter un article...',
    'ok': 'OK',
    'already_bought': 'DÉJÀ ACHETÉ',
    'delete_item_title': 'Supprimer l\'article ?',
    'delete_item_confirm_1': 'Voulez-vous vraiment retirer',
    'delete_item_confirm_2': 'de la liste ?',
    'edit_item_title': 'Modifier l\'article',
    'product_name': 'Nom du produit',
    'quantity': 'Quantité',
    'unit': 'Unité',
    'unit_price': 'Prix Unitaire',
    'save': 'Sauvegarder',
    'how_much': 'Combien ?',
    'unit_price_short': 'Prix Unit.',
    'validate': 'Valider',
    'total_spent_month': 'TOTAL DÉPENSÉ (MOIS)',
    'avg_basket': 'Panier Moyen',
    'top_product': 'Top Produit',
    'most_bought_month': 'Le plus acheté ce mois-ci',
    'product_analysis': 'Analyse Produit',
    'details_by_item': 'Détails par article',
    'charts': 'Graphiques',
    'detailed_visuals': 'Visuels détaillés',
    'period_analysis': 'Analyse de Période',
    'select_date_range': 'Sélectionnez une plage de dates',
    'from': 'Du',
    'to': 'Au',
    'generate_report': 'Générer le rapport',
    'total_period': 'Total Période',
    'no_product_period': 'Aucun produit acheté sur cette période.',
    'export_pdf': 'Exporter en PDF',
    'home': 'Accueil',
    'product_report': 'Rapport Produits',
    'period_from': 'Période du',
    'to_small': 'au',
    'product': 'Produit',
    'total_amount': 'Montant Total',
    'analyze_error': 'Impossible d\'analyser la période',
    'export_error_msg': 'Veuillez d\'abord lancer une analyse de période pour exporter.',
    'pdf_error': 'Impossible de générer le PDF',
    'statistics': 'Statistiques',
    'total_global': 'Total Global',
    'total_year': 'Total Année',
    'distribution': 'Répartition',
    'week': 'Semaine',
    'month': 'Mois',
    'filter': 'Filtrer',
    'manage_display': 'Gérer l\'affichage',
    'last_4_weeks': '4 Dernières Semaines',
    'last_3_months': '3 Derniers Mois',
    'purchase_s': 'achat(s)',
    'see_details': 'Voir détail',
    'deselect_all': 'Tout désélectionner',
    'select_all': 'Tout sélectionner',
    'selected': 'sélectionné(s)',
    'of_total': 'du total',
    'navigation': 'Navigation',
    'no_product_bought': 'Aucun produit acheté.',
    'pdf_export_failed': 'Export PDF échoué',
    'new_list_title': 'Nouvelle liste',
    'create_list_subtitle': 'Créez votre liste d\'achat',
    'list_name_label': 'Nom de la liste d\'achat',
    'list_name_placeholder': 'Ex: Courses du weekend, Repas de famille...',
    'characters': 'caractères',
    'ai_suggestions': '✨ Suggestions (AI Kely)',
    'list_preview': 'Aperçu de votre liste',
    'list_name_default': 'Nom de la liste',
    'creating': 'Création...',
    'create_list_btn': 'Créer la liste',
    'error_create_suggested': 'Impossible de créer la liste suggérée',
    'error_enter_name': 'Veuillez saisir un nom pour la liste d\'achat',
    'error_create_list': 'Impossible de créer la liste d\'achat',
    'customization': 'Personnalisation',
    'dark_mode_desc': 'Apparence sombre pour la nuit',
    'available_themes': 'Thèmes Disponibles',
    'notifications': 'Notifications',
    'clear': 'Effacer',
    'see_list': 'Voir la liste',
    'no_notifications': 'Aucune notification',
    'price_history': 'Historique des prix',
    'product_to_analyze': 'Produit à analyser',
    'choose_product': 'Choisir un produit...',
    'period': 'Période',
    'start_analysis': 'Lancer l\'analyse',
    'analyzing': 'Analyse...',
    'results': 'Résultats',
    'no_purchase_found': 'Aucun achat trouvé.',
    'select_product': 'Sélectionner un produit',
    'see_global_stats': 'Voir les Statistiques Globales',
    'back_to_reports': 'Retour aux Rapports',
    'back_to_home': 'Retour à l\'Accueil',
    'error_select_product': 'Veuillez sélectionner un produit',
    'error_analyze': 'Impossible d\'analyser',
    'loading': 'Chargement...'
  },
  mg: {
    'welcome': 'Tonga soa',
    'my_groceries': 'Ny Fiantsenako',
    'search': 'Hitady...',
    'expenses': 'Fandaniana',
    'articles': 'Entana',
    'recent_lists': 'Lisitra Farany',
    'sort': 'Rihana',
    'settings': 'Fikirana',
    'dark_mode': 'Mode Maizina',
    'language': 'Fiteny',
    'currency': 'Vola',
    'help': 'Torohevitra',
    'close': 'Hidiana',
    'empty_list': 'Tsy misy lisitra hita',
    'new_list': 'Lisitra Vaovao',
    'reports': 'Tatitra',
    'choose_theme': 'Hisafidy Loko',
    'delete_list': 'Fafana ity lisitra ity',
    'delete_list_confirm': 'Tena te hamafa ity lisitra ity ve ianao',
    'delete': 'Fafana',
    'cancel': 'Aoka ihany',
    'tips_title': 'Torohevitra E-tsena',
    'tip_1': 'Ampiasao ny bokotra + hanampiana lisitra.',
    'tip_2': 'Tsy ho voatahiry ny lisitra foana.',
    'tip_3': 'Tsindrio ny ... raha hijery safidy (fafana, fampahatsiahivana).',
    'tip_4': 'Jereo ny tatitra handinihana ny fandaniana.',
    'tip_5': 'Ovay ny loko sy ny fiteny ao amin\'ny fikirana.',
    'understood': 'Azoko',
    'sort_by': 'Rihana araka ny',
    'date': 'Daty',
    'name': 'Anarana',
    'amount': 'Vola',
    'reminder': 'Hampahatsiahy (1 ora)',
    'reminder_set': 'Fampahatsiahivana afaka 1 ora.',
    'reminder_title': 'Fampahatsiahivana',
    'reminder_scheduled': 'Fampahatsiahivana voalamina',
    'reminder_notif_text': 'Hampandrenesina ianao amin\'ny',
    'error': 'Hadisoana',
    'info': 'Filazana',
    'reminder_error': 'Tsy afaka manao fampahatsiahivana (daty lasa ?)',
    'total_spent': 'VOLA LANIA',
    'progress': 'Fandrosoana',
    'to_buy': 'HOVIDIANA',
    'add_item_placeholder': 'Hanampy entana...',
    'ok': 'OK',
    'already_bought': 'EFA NOVIDIANA',
    'delete_item_title': 'Hamafa ilay entana ?',
    'delete_item_confirm_1': 'Tena tianao esorina ve',
    'delete_item_confirm_2': 'amin\'ny lisitra ?',
    'edit_item_title': 'Hanova ilay entana',
    'product_name': 'Anaran\'ny entana',
    'quantity': 'Isa',
    'unit': 'Refy',
    'unit_price': 'Vidin\'ny iray',
    'save': 'Tehirizina',
    'how_much': 'Ohatrinona ?',
    'unit_price_short': 'Vidin\'ny 1',
    'validate': 'Ekena',
    'total_spent_month': 'VOLA LANIA (VOLANA)',
    'avg_basket': 'Vidim-piantsenana',
    'top_product': 'Entana Be Mpividy',
    'most_bought_month': 'Ny tena lafo tamin\'ity volana ity',
    'product_analysis': 'Famakafakana Entana',
    'details_by_item': 'Antsipiriany isaky ny entana',
    'charts': 'Kisary',
    'detailed_visuals': 'Sary antsipiriany',
    'period_analysis': 'Famakafakana Fe-potoana',
    'select_date_range': 'Misafidiana daty',
    'from': 'Nanomboka',
    'to': 'Hatramin\'ny',
    'generate_report': 'Hamorona tatitra',
    'total_period': 'Fitambarany tamin\'ny fe-potoana',
    'no_product_period': 'Tsy nisy entana novidiana tamin\'io fotoana io.',
    'export_pdf': 'Avoaka PDF',
    'home': 'Fandraisana',
    'product_report': 'Tatitra Entana',
    'period_from': 'Fe-potoana nanomboka',
    'to_small': 'ka hatramin\'ny',
    'product': 'Entana',
    'total_amount': 'Vola manontolo',
    'analyze_error': 'Tsy afaka mamakafaka ny fe-potoana',
    'export_error_msg': 'Alefaso aloha ny famakafakana vao mamoaka.',
    'pdf_error': 'Tsy afaka mamorona PDF',
    'statistics': 'Statistika',
    'total_global': 'Fitambarany Rehetra',
    'total_year': 'Fitambarany Taona',
    'distribution': 'Fitsinjarana',
    'week': 'Herinandro',
    'month': 'Volana',
    'filter': 'Tantavanina',
    'manage_display': 'Hitantana fisehoana',
    'last_4_weeks': '4 Herinandro Farany',
    'last_3_months': '3 Volana Farany',
    'purchase_s': 'fividianana',
    'see_details': 'Hijery antsipiriany',
    'deselect_all': 'Esory daholo',
    'select_all': 'Safidio daholo',
    'selected': 'voafidy',
    'of_total': 'amin\'ny fitambarany',
    'navigation': 'Fikarohana',
    'no_product_bought': 'Tsy nisy entana novidiana.',
    'pdf_export_failed': 'Tsy nahomby ny famoahana PDF',
    'new_list_title': 'Lisitra vaovao',
    'create_list_subtitle': 'Mamorona ny lisitrao',
    'list_name_label': 'Anaran\'ny lisitra',
    'list_name_placeholder': 'Ohatra: Fiantsenana faran\'ny herinandro...',
    'characters': 'litera',
    'ai_suggestions': '✨ Soso-kevitra (AI Kely)',
    'list_preview': 'Topimaso ny lisitra',
    'list_name_default': 'Anaran\'ny lisitra',
    'creating': 'Mamorona...',
    'create_list_btn': 'Mamorona lisitra',
    'error_create_suggested': 'Tsy afaka mamorona lisitra naroso',
    'error_enter_name': 'Ampidiro ny anaran\'ny lisitra azafady',
    'error_create_list': 'Tsy afaka mamorona lisitra',
    'customization': 'Fanaingoana',
    'dark_mode_desc': 'Endrika maizina ho an\'ny alina',
    'available_themes': 'Loko misy',
    'notifications': 'Fampandrenesana',
    'clear': 'Fafana',
    'see_list': 'Hijery lisitra',
    'no_notifications': 'Tsy misy fampandrenesana',
    'price_history': 'Tantarany vidiny',
    'product_to_analyze': 'Entana hofakafakaina',
    'choose_product': 'Misafidy entana...',
    'period': 'Fe-potoana',
    'start_analysis': 'Alefa ny famakafakana',
    'analyzing': 'Mamakafaka...',
    'results': 'Valiny',
    'no_purchase_found': 'Tsy misy fividianana hita.',
    'select_product': 'Misafidy entana',
    'see_global_stats': 'Hijery Statistika Manontolo',
    'back_to_reports': 'Hiverina any amin\'ny Tatitra',
    'back_to_home': 'Hiverina any amin\'ny Fandraisana',
    'error_select_product': 'Misafidiana entana azafady',
    'error_analyze': 'Tsy afaka mamakafaka',
    'loading': 'Maka...'
  },
  en: {
    'welcome': 'Welcome',
    'my_groceries': 'My Groceries',
    'search': 'Search...',
    'expenses': 'Expenses',
    'articles': 'Items',
    'recent_lists': 'Recent Lists',
    'sort': 'Sort',
    'settings': 'Settings',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'currency': 'Currency',
    'help': 'Help & Tips',
    'close': 'Close',
    'empty_list': 'No lists found',
    'new_list': 'New List',
    'reports': 'Reports',
    'choose_theme': 'Choose Theme',
    'delete_list': 'Delete this list',
    'delete_list_confirm': 'Do you really want to delete the list',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'tips_title': 'E-tsena Tips',
    'tip_1': 'Use the + button to add a list.',
    'tip_2': 'Empty lists will not be saved.',
    'tip_3': 'Tap ... for options (delete, reminder).',
    'tip_4': 'Check reports to analyze your expenses.',
    'tip_5': 'Change theme and language in settings.',
    'understood': 'Understood',
    'sort_by': 'Sort by',
    'date': 'Date',
    'name': 'Name',
    'amount': 'Amount',
    'reminder': 'Set Reminder (1h)',
    'reminder_set': 'Reminder set for 1 hour.',
    'reminder_title': 'Reminder',
    'reminder_scheduled': 'Reminder scheduled',
    'reminder_notif_text': 'You will be notified on',
    'error': 'Error',
    'info': 'Info',
    'reminder_error': 'Cannot schedule reminder (past date?)',
    'total_spent': 'TOTAL SPENT',
    'progress': 'Progress',
    'to_buy': 'TO BUY',
    'add_item_placeholder': 'Add an item...',
    'ok': 'OK',
    'already_bought': 'ALREADY BOUGHT',
    'delete_item_title': 'Delete item?',
    'delete_item_confirm_1': 'Do you really want to remove',
    'delete_item_confirm_2': 'from the list?',
    'edit_item_title': 'Edit item',
    'product_name': 'Product name',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'unit_price': 'Unit Price',
    'save': 'Save',
    'how_much': 'How much?',
    'unit_price_short': 'Unit Price',
    'validate': 'Validate',
    'total_spent_month': 'TOTAL SPENT (MONTH)',
    'avg_basket': 'Average Basket',
    'top_product': 'Top Product',
    'most_bought_month': 'Most bought this month',
    'product_analysis': 'Product Analysis',
    'details_by_item': 'Details by item',
    'charts': 'Charts',
    'detailed_visuals': 'Detailed visuals',
    'period_analysis': 'Period Analysis',
    'select_date_range': 'Select date range',
    'from': 'From',
    'to': 'To',
    'generate_report': 'Generate report',
    'total_period': 'Total Period',
    'no_product_period': 'No products bought during this period.',
    'export_pdf': 'Export to PDF',
    'home': 'Home',
    'product_report': 'Product Report',
    'period_from': 'Period from',
    'to_small': 'to',
    'product': 'Product',
    'total_amount': 'Total Amount',
    'analyze_error': 'Cannot analyze period',
    'export_error_msg': 'Please run a period analysis first to export.',
    'pdf_error': 'Cannot generate PDF',
    'statistics': 'Statistics',
    'total_global': 'Global Total',
    'total_year': 'Total Year',
    'distribution': 'Distribution',
    'week': 'Week',
    'month': 'Month',
    'filter': 'Filter',
    'manage_display': 'Manage display',
    'last_4_weeks': 'Last 4 Weeks',
    'last_3_months': 'Last 3 Months',
    'purchase_s': 'purchase(s)',
    'see_details': 'See details',
    'deselect_all': 'Deselect all',
    'select_all': 'Select all',
    'selected': 'selected',
    'of_total': 'of total',
    'navigation': 'Navigation',
    'no_product_bought': 'No product bought.',
    'pdf_export_failed': 'PDF export failed',
    'new_list_title': 'New list',
    'create_list_subtitle': 'Create your shopping list',
    'list_name_label': 'Shopping list name',
    'list_name_placeholder': 'Ex: Weekend groceries...',
    'characters': 'characters',
    'ai_suggestions': '✨ Suggestions (AI Kely)',
    'list_preview': 'List preview',
    'list_name_default': 'List name',
    'creating': 'Creating...',
    'create_list_btn': 'Create list',
    'error_create_suggested': 'Cannot create suggested list',
    'error_enter_name': 'Please enter a name for the shopping list',
    'error_create_list': 'Cannot create shopping list',
    'customization': 'Customization',
    'dark_mode_desc': 'Dark appearance for night',
    'available_themes': 'Available Themes',
    'notifications': 'Notifications',
    'clear': 'Clear',
    'see_list': 'See list',
    'no_notifications': 'No notifications',
    'price_history': 'Price history',
    'product_to_analyze': 'Product to analyze',
    'choose_product': 'Choose a product...',
    'period': 'Period',
    'start_analysis': 'Start analysis',
    'analyzing': 'Analyzing...',
    'results': 'Results',
    'no_purchase_found': 'No purchase found.',
    'select_product': 'Select a product',
    'see_global_stats': 'See Global Statistics',
    'back_to_reports': 'Back to Reports',
    'back_to_home': 'Back to Home',
    'error_select_product': 'Please select a product',
    'error_analyze': 'Cannot analyze',
    'loading': 'Loading...'
  }
};

export const SettingsProvider = ({ children }: { children: React.ReactNode }) => {
  const [currency, setCurrency] = useState<Currency>('Ar');
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    AsyncStorage.getItem('settings_currency').then(c => c && setCurrency(c as Currency));
    AsyncStorage.getItem('settings_language').then(l => l && setLanguage(l as Language));
  }, []);

  const updateCurrency = (c: Currency) => {
    setCurrency(c);
    AsyncStorage.setItem('settings_currency', c);
  };

  const updateLanguage = (l: Language) => {
    setLanguage(l);
    AsyncStorage.setItem('settings_language', l);
  };

  const t = (key: string) => {
    return (TRANSLATIONS[language] as any)[key] || key;
  };

  return (
    <SettingsContext.Provider value={{ currency, setCurrency: updateCurrency, language, setLanguage: updateLanguage, t }}>
      {children}
    </SettingsContext.Provider>
  );
};
